import fs from "fs";
import path from "path";

export interface AgentTarget {
  id: string;
  label: string;
  aliases: string[];
  examplePath: string;
  resolvePath: (cwd: string) => string;
  isDetected: (cwd: string) => boolean;
}

export interface RenderedAgentTarget {
  agent: AgentTarget;
  filePath: string;
  contents: string;
}

function existsRelative(cwd: string, relativePath: string): boolean {
  return fs.existsSync(path.join(cwd, relativePath));
}

function isDirectoryRelative(cwd: string, relativePath: string): boolean {
  try {
    return fs.statSync(path.join(cwd, relativePath)).isDirectory();
  } catch {
    return false;
  }
}

function normalizeName(value: string): string {
  return value.trim().toLowerCase();
}

const AGENT_TARGETS: AgentTarget[] = [
  {
    id: "agents",
    label: "AGENTS.md-compatible agents",
    aliases: ["codex", "openai", "chatgpt", "portable"],
    examplePath: "AGENTS.md",
    resolvePath: () => "AGENTS.md",
    isDetected: (cwd) => existsRelative(cwd, "AGENTS.md"),
  },
  {
    id: "claude",
    label: "Claude Code",
    aliases: ["anthropic"],
    examplePath: ".claude/CLAUDE.md",
    resolvePath: (cwd) => {
      if (existsRelative(cwd, ".claude/CLAUDE.md") || isDirectoryRelative(cwd, ".claude")) {
        return ".claude/CLAUDE.md";
      }
      return "CLAUDE.md";
    },
    isDetected: (cwd) =>
      existsRelative(cwd, "CLAUDE.md") ||
      existsRelative(cwd, ".claude/CLAUDE.md") ||
      isDirectoryRelative(cwd, ".claude"),
  },
  {
    id: "cursor",
    label: "Cursor",
    aliases: [],
    examplePath: ".cursor/rules/agentctx.mdc",
    resolvePath: (cwd) => {
      if (existsRelative(cwd, ".cursorrules") && !isDirectoryRelative(cwd, ".cursor")) {
        return ".cursorrules";
      }
      return ".cursor/rules/agentctx.mdc";
    },
    isDetected: (cwd) =>
      isDirectoryRelative(cwd, ".cursor") || existsRelative(cwd, ".cursorrules"),
  },
  {
    id: "gemini",
    label: "Gemini CLI",
    aliases: ["google"],
    examplePath: "GEMINI.md",
    resolvePath: () => "GEMINI.md",
    isDetected: (cwd) => existsRelative(cwd, "GEMINI.md"),
  },
  {
    id: "copilot",
    label: "GitHub Copilot",
    aliases: ["github"],
    examplePath: ".github/copilot-instructions.md",
    resolvePath: () => ".github/copilot-instructions.md",
    isDetected: (cwd) =>
      existsRelative(cwd, ".github/copilot-instructions.md") ||
      isDirectoryRelative(cwd, ".github/agents"),
  },
];

const AGENT_INDEX = new Map<string, AgentTarget>();
for (const agent of AGENT_TARGETS) {
  AGENT_INDEX.set(agent.id, agent);
  for (const alias of agent.aliases) {
    AGENT_INDEX.set(alias, agent);
  }
}

function formatForTarget(filePath: string, markdown: string): string {
  const normalizedMarkdown = markdown.endsWith("\n") ? markdown : markdown + "\n";

  if (filePath.endsWith(".mdc")) {
    const body = markdown.trim();
    return [
      "---",
      "description: Project instructions generated by agentctx",
      "alwaysApply: true",
      "---",
      "",
      "# Project Context",
      "",
      body,
      "",
    ].join("\n");
  }

  return normalizedMarkdown;
}

export function listSupportedAgents(): AgentTarget[] {
  return [...AGENT_TARGETS];
}

export function resolveAgent(name: string): AgentTarget | undefined {
  return AGENT_INDEX.get(normalizeName(name));
}

export function detectAgents(cwd: string = process.cwd()): AgentTarget[] {
  return AGENT_TARGETS.filter((agent) => agent.isDetected(cwd));
}

export function renderAgentTarget(
  agent: AgentTarget,
  markdown: string,
  cwd: string = process.cwd()
): RenderedAgentTarget {
  const filePath = agent.resolvePath(cwd);
  return {
    agent,
    filePath,
    contents: formatForTarget(filePath, markdown),
  };
}
