'use strict';
const fs = require('fs');
const path = require('path');
const store = require('../store');
const { c } = require('../format');

const AGENT_GUIDE = `
## agenctx

Use agenctx to retrieve this repository's project context. This generated guide is static; repository context is stored only in \`.agenctx/\`.

At the start of every interaction:

\`\`\`sh
agenctx --agent start "<task>"
agenctx view --session=<id>
\`\`\`

Remember the session ID printed by \`start\` and pass \`--session=<id>\` to every later agenctx command. This keeps concurrent agents isolated. If exactly one session is active, agenctx accepts commands without the flag for backward compatibility.

\`agenctx view\` is the directory. It shows the project description, pinned context, and every available context type, including repository-defined custom types and their purpose. Do not assume a type name; discover it here.

Open relevant pinned entries and context in full:

\`\`\`sh
agenctx view <type> --session=<id>
agenctx view <id> --session=<id>
\`\`\`

Search across all context when the right type or entry is unclear:

\`\`\`sh
agenctx search "<keyword>" --session=<id>
agenctx search "<keyword>" --banner=<type> --session=<id>
agenctx view <type> --about="<keyword>" --session=<id>
\`\`\`

These discovery commands return previews: \`agenctx view\`, \`agenctx view <type>\`, and \`agenctx search\`. A preview may be truncated and is never the authoritative instruction. Never act on a relevant preview alone. Select only the entries relevant to the task, then retrieve each one in full before acting:

\`\`\`sh
agenctx view <entry-id> --session=<id>
\`\`\`

Do not open every search result. Open the smallest relevant set. Only a full entry read refreshes its lifecycle and appears as \`FULL\` in the session receipt; discovery results appear as \`PREVIEW\`.

Before ending the session, you may propose up to two pieces of durable, repository-specific knowledge discovered during the task:

\`\`\`sh
agenctx propose <type> "knowledge future agents should know" --session=<id>
\`\`\`

Most tasks require no proposal. Never propose temporary task details, generic advice, uncertain conclusions, or information already present. Proposals require human approval and are not served as project context while pending.

While the agent session is active, agenctx records each response it serves in sequence. When the interaction is complete, always run:

\`\`\`sh
agenctx --agent end --session=<id>
\`\`\`
`.trim();

const TARGETS = {
  'agents.md': { file: 'AGENTS.md', type: 'md' },
  claude: { file: 'CLAUDE.md', type: 'md' },
  cursor: { file: '.cursorrules', type: 'cursor' },
};

const ALIASES = {
  agents: 'agents.md',
  openai: 'agents.md',
  codex: 'agents.md',
  'claude.md': 'claude',
  '.cursorrules': 'cursor',
};

const MARKERS = {
  md: {
    start: '<!-- agenctx:start -->',
    end: '<!-- agenctx:end -->',
  },
  cursor: {
    start: '# agenctx:start',
    end: '# agenctx:end',
  },
};

function guideContent(type) {
  const { start, end } = MARKERS[type];
  return `${start}\n${AGENT_GUIDE}\n${end}\n`;
}

function stripManagedContent(existing, type) {
  const { start, end } = MARKERS[type];
  const startIndex = existing.indexOf(start);
  const endIndex = existing.indexOf(end, startIndex + start.length);
  if (startIndex === -1 || endIndex === -1) return existing;
  return (existing.slice(0, startIndex) + existing.slice(endIndex + end.length)).trim();
}

function managedContent(existing, generated, type) {
  const { start, end } = MARKERS[type];
  const block = `${start}\n${generated.trim()}\n${end}`;
  const startIndex = existing.indexOf(start);
  const endIndex = existing.indexOf(end, startIndex + start.length);

  if (startIndex !== -1 && endIndex !== -1) {
    return existing.slice(0, startIndex)
      + block
      + existing.slice(endIndex + end.length);
  }

  // Migrate files created by the original overwrite-only implementation.
  if (existing.startsWith('<!-- Generated by agenctx') || existing.startsWith('# Generated by agenctx')) {
    return block + '\n';
  }

  if (!existing.trim()) return block + '\n';
  return existing.replace(/\s*$/, '') + '\n\n' + block + '\n';
}

function dump(args) {
  const root = store.requireRoot();
  const requested = (args.find(arg => !arg.startsWith('-')) || 'all').toLowerCase();
  const target = ALIASES[requested] || requested;
  const check = args.includes('--check');
  const keys = target === 'all' ? Object.keys(TARGETS) : [target];

  for (const key of keys) {
    if (!TARGETS[key]) {
      console.error(c.red(`Unknown target: ${requested}`));
      console.error(`Available: openai, claude, cursor, all`);
      process.exit(1);
    }
  }

  const generated = [];
  const outdated = [];
  for (const key of keys) {
    const { file, type } = TARGETS[key];
    const filePath = path.join(root, file);
    const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
    const content = managedContent(existing, AGENT_GUIDE, type);

    if (content !== existing) {
      outdated.push(file);
      if (!check) fs.writeFileSync(filePath, content, 'utf8');
    }
    generated.push(file);
    if (!check) console.log(c.green('✓') + ` ${file}`);
  }

  if (check) {
    if (outdated.length) {
      throw new Error(`Generated context is out of date: ${outdated.join(', ')}. Run: agenctx dump ${target}`);
    }
    console.log(c.green('✓') + ' Generated context is up to date');
    return;
  }

  store.appendHistory(root, {
    action: 'dump',
    author: process.env.USER || process.env.USERNAME || 'user',
    command: `dump ${target}`,
    files: generated,
  });
}

module.exports = { dump, guideContent, stripManagedContent };
