'use strict';
const fs = require('fs');
const path = require('path');
const store = require('../store');
const { c } = require('../format');

const AGENT_GUIDE = `
## agenctx

Use agenctx as the project's shared memory. Do not edit \`.agenctx/\` directly.

At the start of a task:

\`\`\`sh
agenctx session start "<task>"
agenctx view
\`\`\`

\`agenctx view\` shows the project description, pinned context, and every context type. Open what is relevant:

\`\`\`sh
agenctx view warnings
agenctx view decisions
agenctx view rules
agenctx view <id> --agent
\`\`\`

Save useful context as you work:

\`\`\`sh
agenctx add warning "<important gotcha>"
agenctx add decision "<choice and reason>"
agenctx add note "<useful context>"
agenctx add task "<follow-up work>"
agenctx add <type> --pin "<always-visible context>"
\`\`\`

When the task is complete, run \`agenctx session end\`.
`.trim();

const TARGETS = {
  'agents.md': { file: 'AGENTS.md', type: 'md' },
  claude: { file: 'CLAUDE.md', type: 'md' },
  cursor: { file: '.cursorrules', type: 'cursor' },
};

const ALIASES = {
  agents: 'agents.md',
  openai: 'agents.md',
  codex: 'agents.md',
  'claude.md': 'claude',
  '.cursorrules': 'cursor',
};

const MARKERS = {
  md: {
    start: '<!-- agenctx:start -->',
    end: '<!-- agenctx:end -->',
  },
  cursor: {
    start: '# agenctx:start',
    end: '# agenctx:end',
  },
};

function managedContent(existing, generated, type) {
  const { start, end } = MARKERS[type];
  const block = `${start}\n${generated.trim()}\n${end}`;
  const startIndex = existing.indexOf(start);
  const endIndex = existing.indexOf(end, startIndex + start.length);

  if (startIndex !== -1 && endIndex !== -1) {
    return existing.slice(0, startIndex)
      + block
      + existing.slice(endIndex + end.length);
  }

  // Migrate files created by the original overwrite-only implementation.
  if (existing.startsWith('<!-- Generated by agenctx') || existing.startsWith('# Generated by agenctx')) {
    return block + '\n';
  }

  if (!existing.trim()) return block + '\n';
  return existing.replace(/\s*$/, '') + '\n\n' + block + '\n';
}

function dump(args) {
  const root = store.requireRoot();
  const requested = (args.find(arg => !arg.startsWith('-')) || 'all').toLowerCase();
  const target = ALIASES[requested] || requested;
  const check = args.includes('--check');
  const keys = target === 'all' ? Object.keys(TARGETS) : [target];

  for (const key of keys) {
    if (!TARGETS[key]) {
      console.error(c.red(`Unknown target: ${requested}`));
      console.error(`Available: openai, claude, cursor, all`);
      process.exit(1);
    }
  }

  const generated = [];
  const outdated = [];
  for (const key of keys) {
    const { file, type } = TARGETS[key];
    const filePath = path.join(root, file);
    const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
    const content = managedContent(existing, AGENT_GUIDE, type);

    if (content !== existing) {
      outdated.push(file);
      if (!check) fs.writeFileSync(filePath, content, 'utf8');
    }
    generated.push(file);
    if (!check) console.log(c.green('✓') + ` ${file}`);
  }

  if (check) {
    if (outdated.length) {
      throw new Error(`Generated context is out of date: ${outdated.join(', ')}. Run: agenctx dump ${target}`);
    }
    console.log(c.green('✓') + ' Generated context is up to date');
    return;
  }

  store.appendHistory(root, {
    action: 'dump',
    author: process.env.USER || process.env.USERNAME || 'user',
    command: `dump ${target}`,
    files: generated,
  });
}

module.exports = { dump };
